### ISSUE TITLE
PF2 issues with Sad 1.1.0

### ISSUE THREAD

**Issue by apoapostolov** [bmarian/sadness-chan#10]
!sadness doesn't work, and doesn't trigger any message. Also 1.1.0 in your site description is listed for 0.7 onwards only, does it mean that 0.6.5 will not get system agnostic features at all?

**Comment by bmarian** [comment]
Hi, the `!sadness` command will not work without some actual rolls first. Roll a few d20s then try the command.

Also 1.1.0 is a 'in between' version right now. It will work in 0.6.4 - 0.7.x.
