### ISSUE TITLE
Disable rolls removing 

### ISSUE THREAD

**Issue by krysztalzg** [bmarian/sadness-chan#19]
Can we have option to disable removing the nat 1/20 rolls from chat?

**Comment by bmarian** [comment]
Hi, I don't exactly understand the issue here. Can you give some more info or an example.

Because from what I understand you are saying that the bot removes rolls? It shouldn't do that.

**Comment by krysztalzg** [comment]
I've got a good sleep and realised what was the root of the issue 🙂  I had _ChatMerger_ add-on enabled and after looking at the code of both plugins it seems that Sadness-chan sends message with actor as origin so the merger was trying to concatenate the roll message with the Sadness-chan quote. Issue resolved for me 👍
