### ISSUE TITLE
Request: Average roll output

### ISSUE THREAD

**Issue by cswendrowski** [bmarian/sadness-chan#21]
One of my players is convinced that the dice hate him, so outputting the player's average roll along with 1's and 20's would be great

**Comment by Noggin01** [comment]
I second this request. It would be great to have them tracked on a per-character basis as well as a global basis.

**Comment by bmarian** [comment]
So for this, we prepared the backbone. All the rolls are tracked per user (a per character tracking would be pretty hard). You have a `!sadness all` command. 

Has no styling for now because I wanted to use that feature to teach someone css. (@HadaIonut *cough* *cough*)

**Comment by bmarian** [comment]
So, maybe soon enough we will also add an average :)
