### ISSUE TITLE
Border around image not looking used with transparent images

### ISSUE THREAD

**Issue by apoapostolov** [bmarian/sadness-chan#27]
The border around the random avatar image is not needed on any full square images, and looks really bad when used with transparent icons or, for example, Discord emoji. See how it looks when using transparent images:

![image](https://user-images.githubusercontent.com/4083812/94339120-2a067b80-0000-11eb-8316-67da12a00f55.png)

**Comment by bmarian** [comment]
The border is a default from foundry. I can add an option to remove it.

![image](https://user-images.githubusercontent.com/33843056/94346856-2f7fb800-0038-11eb-830d-e2278e5961c0.png)

**Comment by apoapostolov** [comment]
Thank you. That's more than enough.
