### ISSUE TITLE
Installin Sadness Chan on 0.7.x install 1.1.3 not 1.1.4 

### ISSUE THREAD

**Issue by apoapostolov** [bmarian/sadness-chan#32]
Although in the mod directory it is shown as version 1.1.4

**Comment by Arkanmann** [comment]
I'm running 0.6.6 and it says 1.1.3 for me and when I click "check update" it gives me the "update" button and when I click it, it claims to have updated, but it still says 1.1.3 and "check update" still gives me the "update" button.
