### ISSUE TITLE
Error when updating modules

### ISSUE THREAD

**Issue by Darkling0057** [bmarian/sadness-chan#35]
Since the last update I get this error in the foundry setup whenever I click update on Sadness-Chan
![image](https://user-images.githubusercontent.com/72898481/96655065-f6f5a480-137f-11eb-8dc2-7ad1a2887b1a.png)

**Comment by bmarian** [comment]
See #34 It's a foundry related chasing error. That page doesn't exist anymore. Uninstall and reinstall the module.
