### ISSUE TITLE
Add support for systems rolling multiple dice or dice types

### ISSUE THREAD

**Issue by autoferrit** [bmarian/sadness-chan#36]
Currently, this only supports a single die, a d20 for example. It would be great if we could configure this to work for multiple dice.

Example, is Savage Worlds, can use d4,d6,d8,d10, and d12. Along with rolling that, the user also rolls a d6 as a player character, known as a wild card (also special NPC's). Such as, if their skill is a d8, they would roll a d8, plus their wildcard d6, and take the best of the two. 

So I think ideally, it would just look at whatever dice are rolled, and use the minimum and maximum as a baseline for a crit fail or success. In savage worlds, there's no critical successes per se, but if you roll a max number on a dice it explodes and can roll another dice. likewise, a critical failure is when both of your dice roll a 1, not just one of them.

Any chance we could try and get support like this (I know it all wouldn't be immediate) would bre pretty awesome. This could work with other systems as well. such as 2d6/3d6 systems, 2d10, or whatever.

**Comment by bmarian** [comment]
This will imply almost a full rewrite of the module for the current implementation. And as of now, we have no plans to continue developing features. Sorry.
