### ISSUE TITLE
Support for dice pool based systems

### ISSUE THREAD

**Issue by r-valyar** [bmarian/sadness-chan#38]
This mod is great, I was introduced to it yesterday. There are many systems that are using dice pool for measuring success and I believe it will be awesome to have support for those:

- Add option in the mod's settings to specify how much successes (or crits on the specified die) are needed to display message. 

For example Coriolis is using pools of d6, if you roll 3 or more it is Crit. Same for other systems.

**Comment by bmarian** [comment]
Hi there, happy you like the module, but we have no plans to develop any new features for it.
