### ISSUE TITLE
Module cannot be downloaded (ez fix)

### ISSUE THREAD

**Issue by ClipplerBlood** [bmarian/sadness-chan#56]
Hi again,
A couple of users reported that they couldn't download the module, with the error

`An unexpected error occurred when downloading file https://github.com/bmarian/sadness-chan/releases/download/1.1.9/sadness-chan-v1.1.9.zip: Not Found`

Upon further inspection I've seen I've used a different versioning tag (1.1.9 instead of **v**1.1.9)

So to fix this issue all that's needed is changing the download url in the module.json to `https://github.com/bmarian/sadness-chan/releases/download/v1.1.9/sadness-chan-v1.1.9.zip`
(notice the v1.1.9)

Sorry for the inconvenience and thanks again for your work!

**Comment by bmarian** [comment]
My bad 😄

**Comment by ClipplerBlood** [comment]
Thanks for the quick fix 🙏
